[supabase]
url = "https://zdztzngmbkmlnkesbtun.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkenR6bmdtYmttbG5rZXNidHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MjMyOTAsImV4cCI6MjA3ODA5OTI5MH0.cniOa6h9WmW8_7ijW1msSKvRTY0u7A-9I5A9FDpgTGQ"

